- .travis.yml
Attempts to fix issue in PDXCapstoneF/SPECtate#13.
> Fix uninstall of pipenv causing travis builds to fail

- .travis.yml
- Pipfile
- Pipfile.lock
Who has two thumbs and forgot to install docopt? @benjspriggs.
Should affect #27 since `docopt` isn't included in the `Pipfile`.
> Add docopt

- .gitignore
- .travis.yml
- dialogue.py
- example_config.json
- mainCLI.py
- runtype_options.json
Replace tabs in code by spaces (for indent)
Change the name of main.py to mainCLI.py to match with the one in dev-gui (so that we can pull from dev to dev-gui without conflict)
Update gitignore for PyCharm and MacOS developers
> Reformat dev and update gitignore

- main.py
- tests/test_main.py
- tests/test_mainCLI.py
> Blackbox Unit Tests

- runtype_options.json
It is actually a copy of HBIR and HBIR_RT.
> Fix LOADLEVEL runtype options.

- objects.py
- speccurses.py
Includes objects 'spec_config' ,  'spec_run', 'props'  and 'prop_item'.   a 'spec_config' includes a list of 'spec_run's .  Each 'spec_run' contains some members and a 'props' member containing the entire list of 'prop_items' available for specjbb.
To save to json:  use json.dump(spec_config_object, cls=spec_encoder).
To load from json: use json.load(file_descriptor, cls=spec_decoder).
> Ht ncurses

- docs/Conversation-on-Props.md
- docs/Conversation-on-Run-Templates.md
- docs/Home.md
- docs/INDEX.md
- docs/Tate-Config.md
- docs/Working-in-Virtual-Environments.md
Here's a minimal example that takes everything from the wiki and puts it into `docs/`.
Per #77.
> Add sample for Github Pages and ReadTheDocs

- example_config.json
> Add annotations

- src/benchmark_run.py
- src/run_generator.py
- src/validate.py
- tests/test_validate.py
This PR adds `times` to a Run object that specifies how many times it should be run. A sample configuration can be found in `test/test_validate.py`.
Addresses #97.
> You can specify how many times to do a specific run

- gui/mainGUI.py
Fix listbox right click for MacOS
Add delete and duplicate for multiple items
Move popup menu creation to __init__ function
> Fix listbox right click and add delete/duplicate on multiple selected items

- gui/run_manager.py
> updates props key

- gui/mainGUI.py
- gui/run_manager.py
File path in title
Save
Save as
Choose and load a different config file then recreate run manager
Update GUI according to the run manager
> Put filepath in title, save, save as, load a different config file, update gui if loading a different config file

- Pipfile
- Pipfile.lock
- tests/test_benchmark_run.py
It'd be a good idea to have unittests for SpecJBBRun, so this PR adds those tests.
> Test java invocations for SpecJBBRun

- gui/mainGUI.py
- gui/run_manager.py
- gui/tooltip.py
Rearrange the form
Implement tooltips
> Rearrange input form and create tooltips for labels

- example_config.json
- gui/mainGUI.py
- gui/run_manager.py
Gotta love :%s (search and replace)
> RunList["args"]["Tag"] -> RunList["tag"]

- dialogue.py
- example_config.json
See commit history in mab-fix-run-format.
> Bring dialogue's run format in line with standard

- dialogue.py
> Fix create_run

- dialogue.py
This also incidentally fixes Issue #174.
> Replace all "runtypes" with "template types."

- dialogue.py
> Add type-checking to dialogue create_run function

- gui/mainGUI.py
- gui/run_manager.py
`on_select` will call `update_run` which I corrected it from what Austin did. Values are saved into the memory on changing run.
When click on another run, if there are fields modified, the run tag in `listbox` turns blue.
> Values are saved on changing run, Run tag turns blue if is modified

- gui/mainGUI.py
It shows a lot of changes to files since I clicked reformat file in my IDE. So it just reformatted some lines. But all this PR does is allow select-all for arg form args.
> arg form: select_all
